version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - Wharenn
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.2.4
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.13
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
  - dependency-name: stylelint
    versions:
    - 13.9.0
  - dependency-name: postcss
    versions:
    - 8.2.4
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
