language: node_js
node_js:
  - lts/*
before_script:
  - npm run build
jobs:
  include:
    - stage: Unit Tests
      script:
        - npm run test:all
        - npm run coveralls
deploy:
  provider: releases
  api_key:
    secure: uAfGQHbfMISxuhLi+wGgPjszzf8hV9ix1lxO6AXvAnp5CpqNuuExE629xFV6XH04N474D9SFKzyyUfESDcQAVxfaHXzC7jRZmqjN3WvD/HSGaiORgRk4PIal/CGQo9Hk3mOvhzUhqmyQGhWD8JBJ6DHXzPprYauMcCNdzkZi//suYD84cfW7fv9iCPLbJT2jynbg0Ek4yqOTy92MBjxzcnXnyGkGQ8QkGQ/IqSp6whDB3nIrnyxmMTjZhguJpYNSZzAZoVISoFYw4DSWhQXEkVREYtLjLr7KMvwqGo3IPJkm7cOLgs5qeKxaoF0FBOL+LqXAsWDARDWcnnHvh2funROgiAcLHRVJ5WOUHEVaIaTuJQ+4ZXhpxGZVCZyul1R848VUSLiGBao4hana3r3GAn7AWqmtenX9lMjaz53R1NG9x5ty+Kz+UdP5QzzAOAofpgf4J/+YbnDEem7xXfwTz+ExR1CJjXww6eYffVOS8gB+4XZziqOTm48smZiLlsqGmLIh53FAlvfU1pVGff4WS46+FFTs1eUO0bAv37vuXhwyc+hLFu0sm34ODl4W3F5taI+mYNr/yLMnVlKGKg6RCnJ7nJchyNpAFskBw+VDx68p7/EI0Nmpbu13u9SSMJody5FG601lgfvXuIMvA65AEwIGib7zSoSP9bPutySrl4I=
  file_glob: true
  file: dist/*
  on:
    repo: Wharenn/cookie-consent-tools
    tags: true
